import { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "mock-1",
        productID: "PI-1001",
        name: "Lindt Excellence Dark Chocolate 85% Cocoa",
        title: "Lindt Excellence Dark Chocolate 85% Cocoa",
        brand: "Lindt",
        description: "Experience the ultimate in dark chocolate with Lindt Excellence 85% Cocoa. Rich, intense, and exceptionally smooth.",
        price: 450,
        originalPrice: 550,
        category: "Chocolate Bars",
        stock: 50,
        isActive: true,
        status: 'active',
        slug: "lindt-excellence-85-dark",
        tags: ["imported", "chocolate"],
        searchKeywords: ["lindt", "dark chocolate"],
        totalSales: 10,
        weeklySales: 2,
        monthlySales: 8,
        imageURL: "https://images.unsplash.com/photo-1548907077-39e17aee6bc7?auto=format&fit=crop&w=800&q=80",
        sourceURL: "#",
        sourceWebsite: "Prime Imports",
    },
    {
        id: "mock-2",
        productID: "PI-1002",
        name: "Fortnum & Mason Royal Blend Tea",
        title: "Fortnum & Mason Royal Blend Tea",
        brand: "Fortnum & Mason",
        description: "First blended for King Edward VII in 1902, Royal Blend has been popular ever since for its smooth, honey-like flavour.",
        price: 2800,
        originalPrice: 3200,
        category: "Tea & Coffee",
        stock: 4,
        isActive: true,
        status: 'active',
        slug: "fortnum-mason-royal-blend",
        tags: ["imported", "tea"],
        searchKeywords: ["fortnum", "mason", "tea"],
        totalSales: 5,
        weeklySales: 1,
        monthlySales: 3,
        imageURL: "https://images.unsplash.com/photo-1594631252845-29fc4586210f?auto=format&fit=crop&w=800&q=80",
        sourceURL: "#",
        sourceWebsite: "Prime Imports",
    },
    {
        id: "mock-3",
        productID: "PI-1003",
        name: "Perrier Sparkling Natural Mineral Water",
        title: "Perrier Sparkling Natural Mineral Water",
        brand: "Perrier",
        description: "Perrier is a world-class natural mineral water that contains only mineral salts and natural gas.",
        price: 250,
        originalPrice: 280,
        category: "Beverages & Drinks",
        stock: 100,
        isActive: true,
        status: 'active',
        slug: "perrier-sparkling-750ml",
        tags: ["imported", "water"],
        searchKeywords: ["perrier", "sparkling", "water"],
        totalSales: 20,
        weeklySales: 5,
        monthlySales: 15,
        imageURL: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80",
        sourceURL: "#",
        sourceWebsite: "Prime Imports",
    },
    {
        id: "mock-4",
        productID: "PI-1004",
        name: "Waitrose Duchy Organic All Butter Shortbread",
        title: "Waitrose Duchy Organic All Butter Shortbread",
        brand: "Waitrose Duchy",
        description: "Slow-baked using the finest organic ingredients, these shortbread fingers are light and buttery.",
        price: 1200,
        originalPrice: 1500,
        category: "Biscuits & Cookies",
        stock: 12,
        isActive: true,
        status: 'active',
        slug: "waitrose-duchy-shortbread",
        tags: ["imported", "organic", "biscuits"],
        searchKeywords: ["waitrose", "shortbread", "organic"],
        totalSales: 8,
        weeklySales: 2,
        monthlySales: 6,
        imageURL: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80",
        sourceURL: "#",
        sourceWebsite: "Prime Imports",
    },
    {
        id: "mock-5",
        productID: "PI-1005",
        name: "San Pellegrino Limonata (Pack of 6)",
        title: "San Pellegrino Limonata (Pack of 6)",
        brand: "San Pellegrino",
        description: "Made with the juice of sun-ripened Sicilian lemons, Limonata is the perfect thirst-quencher.",
        price: 1400,
        originalPrice: 1650,
        category: "Beverages & Drinks",
        stock: 30,
        isActive: true,
        status: 'active',
        slug: "san-pellegrino-limonata-pack",
        tags: ["imported", "beverage"],
        searchKeywords: ["san pellegrino", "limonata"],
        totalSales: 15,
        weeklySales: 3,
        monthlySales: 10,
        imageURL: "https://images.unsplash.com/photo-1543253337-024213241883?auto=format&fit=crop&w=800&q=80",
        sourceURL: "#",
        sourceWebsite: "Prime Imports",
    },
    {
        id: "mock-6",
        productID: "PI-1006",
        name: "Kellogg's Special K Red Berries",
        title: "Kellogg's Special K Red Berries",
        brand: "Kellogg's",
        description: "A delicious blend of light, crispy flakes and pieces of sun-ripened strawberries. Rich in vitamins and minerals.",
        price: 850,
        originalPrice: 1050,
        category: "Breakfast & Cereals",
        stock: 45,
        isActive: true,
        status: 'active',
        slug: "kelloggs-special-k-berries",
        tags: ["imported", "cereal"],
        searchKeywords: ["kelloggs", "special k", "cereal"],
        totalSales: 12,
        weeklySales: 4,
        monthlySales: 10,
        imageURL: "https://images.unsplash.com/photo-1586444248902-2f64eddf13cf?auto=format&fit=crop&w=800&q=80",
        sourceURL: "#",
        sourceWebsite: "Prime Imports",
    },
    {
        id: "mock-7",
        productID: "PI-1007",
        name: "L'Occitane Shea Butter Hand Cream",
        title: "L'Occitane Shea Butter Hand Cream",
        brand: "L'Occitane",
        description: "Concentrated with 20% organic Shea Butter, this super-creamy balm penetrates quickly to protect, nourish and moisturize hands.",
        price: 3200,
        originalPrice: 3800,
        category: "Cosmetics & Beauty",
        stock: 8,
        isActive: true,
        status: 'active',
        slug: "loccitane-hand-cream",
        tags: ["imported", "luxury", "skincare"],
        searchKeywords: ["loccitane", "hand cream", "shea butter"],
        totalSales: 6,
        weeklySales: 1,
        monthlySales: 4,
        imageURL: "https://images.unsplash.com/photo-1512496011931-d00780be645c?auto=format&fit=crop&w=800&q=80",
        sourceURL: "#",
        sourceWebsite: "Prime Imports",
    },
    {
        id: "mock-8",
        productID: "PI-1008",
        name: "Philadelphia Original Cream Cheese",
        title: "Philadelphia Original Cream Cheese",
        brand: "Philadelphia",
        description: "Made with milk and cream, Philadelphia is the original cream cheese that's smooth, creamy and delicious. Perfect for cheesecakes or bagels.",
        price: 650,
        originalPrice: 750,
        category: "Dairy & Cheese",
        stock: 15,
        isActive: true,
        status: 'active',
        slug: "philadelphia-cream-cheese",
        tags: ["imported", "dairy"],
        searchKeywords: ["philadelphia", "cream cheese"],
        totalSales: 18,
        weeklySales: 4,
        monthlySales: 12,
        imageURL: "https://images.unsplash.com/photo-1552763407-3d183307ec9b?auto=format&fit=crop&w=800&q=80",
        sourceURL: "#",
        sourceWebsite: "Prime Imports",
    }
];
